version: '3.8'

services:
  threagile:
    image: ghcr.io/threagile/threagile:latest
    container_name: threagile
    volumes:
      - ./model.yaml:/app/model.yaml
      - ./output:/app/output
    command: [ "threagile", "-model", "model.yaml", "-output", "output" ]
