name: LaTeX Compile

on:
  push:
    branches:
      - '*'  # auf allen Branches ausführen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: LaTeX kompilieren
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: PDF als Artefakt speichern
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: main.pdf
